SITE/routes/web.php
<?php


use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', 'HomeController@show');
    Route::get('/home', 'HomeController@show')->name('home');
    Route::get('/page/{url}', 'PagesController@show')->name('page');
    Route::get('/reports/{slug}', 'ProductsController@show')->name('reports');

    Route::get('/article/{url}', 'ArticlesController@show')->name('article');
    Route::get('/article/category/{id}', 'ArticlesController@byCategory');



});

Route::get('/home/search', 'HomeController@search')->name('search');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('/contactform', 'FormsController@contactForm')->name('contactform');

/* AUTH ROUTES */
Auth::routes();
/* END AUTH ROUTES */

/* ADMIN ROUTES _________________________________________________________________________________________ */
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
        Route::get('/', 'Admin\HomeController@show');
    /* PAGES ___________________________________________________________________________________________*/
        Route::post('/pages/sort', 'Admin\PagesController@sort');
        Route::resource('/pages', 'Admin\PagesController');
    /* END PAGES ___________________________________________________________________________________________*/
    /* CATEGORIES ___________________________________________________________________________________________*/
        // Route::post('/categories/sort', 'Admin\CategoriesController@sort');
        // Route::resource('/categories', 'Admin\CategoriesController');
    /* END CATEGORIES ___________________________________________________________________________________________*/
    /* ARTICLES ___________________________________________________________________________________________*/
        Route::get('/articles/search', 'Admin\ArticlesController@search')->name('articles.search');
        Route::get('/articles/searcharticle', 'Admin\ArticlesController@searchArticle');
        Route::get('/articles/setnext/{id}', 'Admin\ArticlesController@setnext')->name('articles.setnext');
        Route::post('/articles/searchparent', 'Admin\ArticlesController@searchparent');
        Route::get('/articles/setstatus/{id}', 'Admin\ArticlesController@setStatus')->name('articles.setstatus');
        Route::get('/articles/setinteresting/{id}', 'Admin\ArticlesController@setInteresting')->name('articles.setinteresting');
        Route::get('/articles/setpress/{id}', 'Admin\ArticlesController@setPress')->name('articles.setpress');
        Route::post('/articles/sort/{id}', 'Admin\ArticlesController@sort')->name('articles.sort');
        Route::post('/articles/fakeviews/{id}', 'Admin\ArticlesController@fakeViews')->name('articles.fakeviews');
        Route::get('/articles/popup/{id}', 'Admin\ArticlesController@popup')->name('articles.popup');
        Route::resource('/articles', 'Admin\ArticlesController');
    /* END ARTICLES ___________________________________________________________________________________________*/
    /* REPORTS ___________________________________________________________________________________________*/
        Route::get('/reports/search', 'Admin\ReportsController@search')->name('reports.search');
        Route::get('/reports/setstatus/{id}', 'Admin\ReportsController@setStatus')->name('reports.setstatus');
        Route::post('/reports/sort/{id}', 'Admin\ReportsController@sort')->name('reports.sort');
        Route::resource('/reports', 'Admin\ReportsController');
    /* END REPORTS ___________________________________________________________________________________________*/
    /* BRIEFS ___________________________________________________________________________________________*/
        Route::get('/briefs/search', 'Admin\BriefsController@search')->name('briefs.search');
        Route::get('/briefs/setstatus/{id}', 'Admin\BriefsController@setStatus')->name('briefs.setstatus');
        Route::post('/briefs/sort/{id}', 'Admin\BriefsController@sort')->name('briefs.sort');
        Route::resource('/briefs', 'Admin\BriefsController');
    /* END BRIEFS ___________________________________________________________________________________________*/
    /* VIDEOS ___________________________________________________________________________________________*/
        Route::get('/videos/search', 'Admin\VideosController@search')->name('videos.search');
        Route::get('/videos/async', 'Admin\VideosController@async')->name('videos.async');
        Route::resource('/videos', 'Admin\VideosController');
    /* END VIDEOS ___________________________________________________________________________________________*/
    /* SLIDES ___________________________________________________________________________________________*/
        Route::get('/slides/search', 'Admin\SlidesController@search')->name('slides.search');
        Route::get('/slides/async', 'Admin\SlidesController@async')->name('slides.async');
        Route::resource('/slides', 'Admin\SlidesController');
    /* END SLIDES ___________________________________________________________________________________________*/
    /* BANNERS ___________________________________________________________________________________________*/
        // Route::get('/banners/search', 'Admin\BannersController@search')->name('banners.search');
        // Route::get('/banners/async', 'Admin\BannersController@async')->name('banners.async');
        // Route::resource('/banners', 'Admin\BannersController');
    /* END BANNERS ___________________________________________________________________________________________*/
    /* LOCALES ___________________________________________________________________________________________*/
        Route::get('/locale/setstatus/{id}', 'Admin\LocaleController@setStatus');
        Route::post('/locale/sort', 'Admin\LocaleController@sort');
        Route::resource('/locale', 'Admin\LocaleController');
    /* END LOCALES ___________________________________________________________________________________________*/
    /* USERS ___________________________________________________________________________________________*/
        Route::get('/users/delete/{id}', 'Admin\UsersController@destroy')->name('users.delete');
        Route::resource('/users', 'Admin\UsersController');
        Route::get('/mediamanager', 'Admin\MediaController@show')->name('mediamanager.index');
    /* END USERS ___________________________________________________________________________________________*/
    /* GALLERIES ___________________________________________________________________________________________*/
        Route::get('/galleries/getAll', 'Admin\GalleryController@getAllGalleriesInJson');
        Route::get('/galleries/setmonth/{id}', 'Admin\GalleryController@setMonth');
        Route::resource('/galleries', 'Admin\GalleryController');
    /* END GALLERIES ___________________________________________________________________________________________*/
    /* SETTINGS ___________________________________________________________________________________________*/
        Route::get('/settings/{name}', 'Admin\SettingController@settingsfor')->name('settings.for');
        Route::get('/settings', 'Admin\SettingController@index')->name('settings');
        Route::put('/settings/{name}', 'Admin\SettingController@update')->name('settings.update');
    /* END SETTINGS ___________________________________________________________________________________________*/

});

SITE/resources/views/admin/partials/locale-toggler.blade.php
<div class="uk-margin">
    <ul class="uk-subnav uk-subnav-pill">
        <li>
            <locale-toggler available-locales="{{json_encode($locales)}}"></locale-toggler>
        </li>
    </ul>
</div>

SITE/resources/views/admin/partials/main-nav.blade.php
<div class="uk-container uk-container-large">
    <a href="#offcanvas-usage" class="uk-margin-medium-right" uk-toggle uk-icon="icon: menu; ratio: 2"></a>
    <div class="uk-position-top-right">
        <div class="uk-inline uk-margin-medium-right uk-margin-small-top">
            <button class="uk-button uk-button-default" type="button"><span class="uk-margin-small-right"
                                                                            uk-icon="icon: user"></span>
                {{Auth::user()->name}}::<span class="uk-text-danger">{{Auth::user()->role->name}}</span>
            </button>
            <div uk-dropdown="mode: hover; animation: uk-animation-slide-top-small; duration: 1000" class="uk-padding-remove">
                <ul class="uk-nav uk-dropdown-nav uk-padding-remove">
                    <li>
                        <a href="{{ route('logout') }}">
                            <span class="uk-margin-small-right"
                            uk-icon="icon: sign-out"></span> Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div id="offcanvas-usage" uk-offcanvas="mode: reveal; overlay: false" uk-offcanvas>
        <div class="uk-offcanvas-bar">
            <button class="uk-offcanvas-close" type="button" uk-close></button>
            <h1>ECMS</h1>
            <div>
                <ul class="uk-nav-default uk-nav-parent-icon" uk-nav>
                    @if(Auth::user()->role->name != 'Editor')
                    <li class="uk-active uk-parent">
                        <a href="#"><span class="uk-margin-small-right" uk-icon="icon: file"></span>Pages</a>
                        <ul class="uk-nav-sub">
                            <li><a href="{{route('pages.index')}}">
                                    <span class="uk-margin-small-right"
                                    uk-icon="icon: list"></span>All</a></li>
                            <li><a href="{{route('pages.create')}}">
                                    <span class="uk-margin-small-right"
                                    uk-icon="icon: plus-circle"></span>New</a>
                            </li>
                        </ul>
                    </li>
                    @endif
                    <li class="uk-parent">
                        <a href="#"><span class="uk-margin-small-right" uk-icon="icon: link"></span>Articles</a>
                        <ul class="uk-nav-sub">
                            <li><a href="{{route('articles.index')}}"><span class="uk-margin-small-right"
                                                                            uk-icon="icon: list"></span>All</a></li>
                            <li><a href="{{route('articles.create')}}"><span class="uk-margin-small-right"
                                                                             uk-icon="icon: plus-circle"></span>New</a>
                            </li>
                        </ul>
                    </li>
                    <li class="uk-parent">
                        <a href="#"><span class="uk-margin-small-right" uk-icon="icon: lifesaver"></span>Annual Reports</a>
                        <ul class="uk-nav-sub">
                            <li><a href="{{route('reports.index')}}"><span class="uk-margin-small-right"
                                                                            uk-icon="icon: list"></span>All</a></li>
                            <li><a href="{{route('reports.create')}}"><span class="uk-margin-small-right"
                                                                             uk-icon="icon: plus-circle"></span>New</a>
                            </li>
                        </ul>
                    </li>
                    <li class="uk-parent">
                        <a href="#"><span class="uk-margin-small-right" uk-icon="icon: bolt"></span>Press Briefly</a>
                        <ul class="uk-nav-sub">
                            <li><a href="{{route('briefs.index')}}"><span class="uk-margin-small-right"
                                                                            uk-icon="icon: list"></span>All</a></li>
                            <li><a href="{{route('briefs.create')}}"><span class="uk-margin-small-right"
                                                                             uk-icon="icon: plus-circle"></span>New</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{{route('videos.index')}}"><span class="uk-margin-small-right"
                                                                  uk-icon="icon: play"></span>Videos</a>
                    </li>
                    <li>
                        <a href="{{route('settings.for','main-slider')}}"><span class="uk-margin-small-right"
                                                                  uk-icon="icon: image"></span>Slider</a>
                    </li>
                    <li>
                        <a href="{{route('galleries.index')}}"><span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span>Galleries</a>
                    </li>
                    @if(Auth::user()->role->name != 'Editor' && Auth::user()->role->name != 'Moderator')
                    <li>
                        <a href="{{route('users.index')}}"><span class="uk-margin-small-right"
                                                                     uk-icon="icon: user"></span>Users</a>
                    </li>
                    @endif
                    <li>
                        <a href="{{route('mediamanager.index')}}"><span class="uk-margin-small-right"
                                                                        uk-icon="icon: camera"></span>Mediamanager</a>
                    </li>
                    @if(Auth::user()->role->name != 'Editor')
                    <li>
                        <a href="{{route('locale.index')}}"><span class="uk-margin-small-right"
                                                                      uk-icon="icon: world"></span>Localization</a>
                    </li>

                    <li>
                        <a href="{{route('settings')}}"><span class="uk-margin-small-right"
                                                                        uk-icon="icon: cog"></span>Settings</a>
                    </li>
                    @endif
                </ul>
            </div>
        </div>
    </div>
</div>

SITE/resources/views/admin/partials/notifications.blade.php
@if (session('notification'))
    <script>
        var not = {!! json_encode(session('notification')) !!};
        UIkit.notification({
            message: not.message,
            status: not.type,
            pos: 'top-right',
            timeout: 3000
        });
    </script>
@endif