SITE/routes/web.php
<?php


use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', 'HomeController@show');
    Route::get('/home', 'HomeController@show')->name('home');
    Route::get('/page/{url}', 'PagesController@show')->name('page');
    Route::get('/reports/{slug}', 'ProductsController@show')->name('reports');

    Route::get('/article/{url}', 'ArticlesController@show')->name('article');
    Route::get('/article/category/{id}', 'ArticlesController@byCategory');



});

Route::get('/home/search', 'HomeController@search')->name('search');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('/contactform', 'FormsController@contactForm')->name('contactform');

/* AUTH ROUTES */
Auth::routes();
/* END AUTH ROUTES */

/* ADMIN ROUTES _________________________________________________________________________________________ */
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
        Route::get('/', 'Admin\HomeController@show');
    /* PAGES ___________________________________________________________________________________________*/
        Route::post('/pages/sort', 'Admin\PagesController@sort');
        Route::resource('/pages', 'Admin\PagesController');
    /* END PAGES ___________________________________________________________________________________________*/
    /* CATEGORIES ___________________________________________________________________________________________*/
        // Route::post('/categories/sort', 'Admin\CategoriesController@sort');
        // Route::resource('/categories', 'Admin\CategoriesController');
    /* END CATEGORIES ___________________________________________________________________________________________*/
    /* ARTICLES ___________________________________________________________________________________________*/
        Route::get('/articles/search', 'Admin\ArticlesController@search')->name('articles.search');
        Route::get('/articles/searcharticle', 'Admin\ArticlesController@searchArticle');
        Route::get('/articles/setnext/{id}', 'Admin\ArticlesController@setnext')->name('articles.setnext');
        Route::post('/articles/searchparent', 'Admin\ArticlesController@searchparent');
        Route::get('/articles/setstatus/{id}', 'Admin\ArticlesController@setStatus')->name('articles.setstatus');
        Route::get('/articles/setinteresting/{id}', 'Admin\ArticlesController@setInteresting')->name('articles.setinteresting');
        Route::get('/articles/setpress/{id}', 'Admin\ArticlesController@setPress')->name('articles.setpress');
        Route::post('/articles/sort/{id}', 'Admin\ArticlesController@sort')->name('articles.sort');
        Route::post('/articles/fakeviews/{id}', 'Admin\ArticlesController@fakeViews')->name('articles.fakeviews');
        Route::get('/articles/popup/{id}', 'Admin\ArticlesController@popup')->name('articles.popup');
        Route::resource('/articles', 'Admin\ArticlesController');
    /* END ARTICLES ___________________________________________________________________________________________*/
    /* REPORTS ___________________________________________________________________________________________*/
        Route::get('/reports/search', 'Admin\ReportsController@search')->name('reports.search');
        Route::get('/reports/setstatus/{id}', 'Admin\ReportsController@setStatus')->name('reports.setstatus');
        Route::post('/reports/sort/{id}', 'Admin\ReportsController@sort')->name('reports.sort');
        Route::resource('/reports', 'Admin\ReportsController');
    /* END REPORTS ___________________________________________________________________________________________*/
    /* BRIEFS ___________________________________________________________________________________________*/
        Route::get('/briefs/search', 'Admin\BriefsController@search')->name('briefs.search');
        Route::get('/briefs/setstatus/{id}', 'Admin\BriefsController@setStatus')->name('briefs.setstatus');
        Route::post('/briefs/sort/{id}', 'Admin\BriefsController@sort')->name('briefs.sort');
        Route::resource('/briefs', 'Admin\BriefsController');
    /* END BRIEFS ___________________________________________________________________________________________*/
    /* VIDEOS ___________________________________________________________________________________________*/
        Route::get('/videos/search', 'Admin\VideosController@search')->name('videos.search');
        Route::get('/videos/async', 'Admin\VideosController@async')->name('videos.async');
        Route::resource('/videos', 'Admin\VideosController');
    /* END VIDEOS ___________________________________________________________________________________________*/
    /* SLIDES ___________________________________________________________________________________________*/
        Route::get('/slides/search', 'Admin\SlidesController@search')->name('slides.search');
        Route::get('/slides/async', 'Admin\SlidesController@async')->name('slides.async');
        Route::resource('/slides', 'Admin\SlidesController');
    /* END SLIDES ___________________________________________________________________________________________*/
    /* BANNERS ___________________________________________________________________________________________*/
        // Route::get('/banners/search', 'Admin\BannersController@search')->name('banners.search');
        // Route::get('/banners/async', 'Admin\BannersController@async')->name('banners.async');
        // Route::resource('/banners', 'Admin\BannersController');
    /* END BANNERS ___________________________________________________________________________________________*/
    /* LOCALES ___________________________________________________________________________________________*/
        Route::get('/locale/setstatus/{id}', 'Admin\LocaleController@setStatus');
        Route::post('/locale/sort', 'Admin\LocaleController@sort');
        Route::resource('/locale', 'Admin\LocaleController');
    /* END LOCALES ___________________________________________________________________________________________*/
    /* USERS ___________________________________________________________________________________________*/
        Route::get('/users/delete/{id}', 'Admin\UsersController@destroy')->name('users.delete');
        Route::resource('/users', 'Admin\UsersController');
        Route::get('/mediamanager', 'Admin\MediaController@show')->name('mediamanager.index');
    /* END USERS ___________________________________________________________________________________________*/
    /* GALLERIES ___________________________________________________________________________________________*/
        Route::get('/galleries/getAll', 'Admin\GalleryController@getAllGalleriesInJson');
        Route::get('/galleries/setmonth/{id}', 'Admin\GalleryController@setMonth');
        Route::resource('/galleries', 'Admin\GalleryController');
    /* END GALLERIES ___________________________________________________________________________________________*/
    /* SETTINGS ___________________________________________________________________________________________*/
        Route::get('/settings/{name}', 'Admin\SettingController@settingsfor')->name('settings.for');
        Route::get('/settings', 'Admin\SettingController@index')->name('settings');
        Route::put('/settings/{name}', 'Admin\SettingController@update')->name('settings.update');
    /* END SETTINGS ___________________________________________________________________________________________*/

});

SITE/resources/views/admin/pages/pages/_form.blade.php
<ul class="uk-switcher uk-margin">
        <li>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Name</div>
                <localized-input input-name="name" 
                class-name="uk-input uk-form-large" 
                id="translit-it" 
                placeholder="Page name"
                available-data="{{$page->name ? json_encode($page->name) : null}}">
                </localized-input>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Slug</div>
                <slug inputname="url" oldval="{{old('url', $page->url)}}"></slug>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Placement</div>
                <select class="uk-select uk-form-large" name="place">
                        <option value="mainmenu" @if($page->place == 'mainmenu') selected @endif>Main menu</option>
                        <option value="category" @if($page->place == 'category') selected @endif>Category</option>
                        <option value="both" @if($page->place == 'both') selected @endif>Main menu & Category</option>
                        <option value="link" @if($page->place == 'link') selected @endif>Link</option>
                </select>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Type</div>
                <select class="uk-select uk-form-large" name="type">
                        <option value="regular" @if($page->type == 'regular') selected @endif>Regular</option>
                        <option value="route" @if($page->type == 'route') selected @endif>Route</option>
                        <option value="custom" @if($page->type == 'custom') selected @endif>Custom</option>
                </select>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Parent</div>
                <select class="uk-select uk-form-large" name="parent_id">
                    <option value="0">No parent</option>
                    @foreach($pages as $item)
                        @continue($page->id === $item->id)
                        <option value="{{$item->id}}"
                                @if($page->parent && $page->parent->id === $item->id) selected @endif>
                                @foreach($locales as $locale)
                               {{$item->name[$locale->slug] or "No translation ($locale->slug)"}} /
                                @endforeach
                            </option>
                    @endforeach
                </select>
            </div>
            <div class="uk-margin">
                <imageinput inputname="cover" btn="Choose Cover"  img="{{old('cover', $page->cover)}}" ></imageinput>
            </div>
            <div class="uk-margin">
                <imageinput inputname="logo" btn="Choose Logo"  img="{{old('cover', $page->logo)}}" ></imageinput>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Cover overlay opacity</div>
                <range class="uk-form-width-small" name="coveropacity" min="0" max="1" step="0.1" default="0.5" default="{{old('coveropacity', $page->coveropacity)}}"></range>
            </div>
        </li>
        <li>
            <localized-textarea 
            input-name="content" 
            class-name="uk-textarea uk-form-large" 
            editor="true" 
            available-data="{{$page->content ? json_encode($page->content) : null}}">
            </localized-textarea>
        </li>
        <li>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Keywords</div>
                <localized-input input-name="keywords"
                    class-name="uk-input uk-form-large" 
                    placeholder="Keywords"
                    available-data="{{$page->keywords ? json_encode($page->keywords) : null}}">
                </localized-input>
            </div>
            <div class="uk-margin">
                <div class="uk-form-label uk-animation-slide-bottom">Description</div>
                <localized-textarea input-name="description" 
                class-name="uk-textarea uk-form-large" 
                placeholder="Description"
                available-data="{{$page->description ? json_encode($page->description) : null}}"
                localized="{{json_encode($locales)}}">
                </localized-textarea>
            </div>
        </li>
    </ul>

SITE/resources/views/admin/pages/pages/create.blade.php
@extends('admin.layouts.base') 
@section('title', '::New Page')
@section('js') 
@parent
<script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
<script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
<script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
 
@section('content')
<div class="uk-section">
    <div class="uk-container head-font">
        @include('admin.partials.locale-toggler')
        <form action="{{route('pages.store')}}" method="post">
            {{ csrf_field() }}
            <ul class="uk-subnav uk-subnav-pill" uk-switcher="animation: uk-animation-slide-bottom-medium">
                <li><a href="#">Title & Cover</a></li>
                <li><a href="#">Content</a></li>
                <li><a href="#">SEO</a></li>
            </ul>
            @include('admin.pages.pages._form')
            <div class="uk-margin">
                <button class="uk-button uk-button-secondary uk-float-right">Save</button>
            </div>
        </form>
    </div>
</div>
@endsection

SITE/resources/views/admin/pages/pages/edit.blade.php
@extends('admin.layouts.base')
@section('title', '::New Page')
@section('js')
    @parent
    <script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
@section('content')
    <div class="uk-section">
        <div class="uk-container head-font">
            @include('admin.partials.locale-toggler')
            <form action="{{route('pages.update', $page->id)}}" method="POST">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <ul class="uk-subnav uk-subnav-pill" uk-switcher="animation: uk-animation-slide-bottom-medium">
                    <li><a href="#">Title & Cover</a></li>
                    <li><a href="#">Content</a></li>
                    <li><a href="#">SEO</a></li>
                </ul>
                @include('admin.pages.pages._form')
                <div class="uk-margin">
                    <a href="{{route('pages.index')}}" class="uk-button uk-button-danger uk-float-left">Exit without
                        saving</a>
                    <button class="uk-button uk-button-secondary uk-float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection

SITE/resources/views/admin/pages/pages/pages.blade.php
@extends('admin.layouts.base')
@section('title','::Pages')
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
            <a href="{{route('pages.create')}}" class="uk-icon-button uk-button-secondary uk-float-right" uk-icon="icon: plus"></a>
        </div>
        <div class="uk-container uk-container-small">
            <tree :pages="{{json_encode($pages)}}" url="pages"></tree>
        </div>
    </div>
@endsection