SITE/routes/web.php
<?php


use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', 'HomeController@show');
    Route::get('/home', 'HomeController@show')->name('home');
    Route::get('/page/{url}', 'PagesController@show')->name('page');
    Route::get('/reports/{slug}', 'ProductsController@show')->name('reports');

    Route::get('/article/{url}', 'ArticlesController@show')->name('article');
    Route::get('/article/category/{id}', 'ArticlesController@byCategory');



});

Route::get('/home/search', 'HomeController@search')->name('search');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('/contactform', 'FormsController@contactForm')->name('contactform');

/* AUTH ROUTES */
Auth::routes();
/* END AUTH ROUTES */

/* ADMIN ROUTES _________________________________________________________________________________________ */
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
        Route::get('/', 'Admin\HomeController@show');
    /* PAGES ___________________________________________________________________________________________*/
        Route::post('/pages/sort', 'Admin\PagesController@sort');
        Route::resource('/pages', 'Admin\PagesController');
    /* END PAGES ___________________________________________________________________________________________*/
    /* CATEGORIES ___________________________________________________________________________________________*/
        // Route::post('/categories/sort', 'Admin\CategoriesController@sort');
        // Route::resource('/categories', 'Admin\CategoriesController');
    /* END CATEGORIES ___________________________________________________________________________________________*/
    /* ARTICLES ___________________________________________________________________________________________*/
        Route::get('/articles/search', 'Admin\ArticlesController@search')->name('articles.search');
        Route::get('/articles/searcharticle', 'Admin\ArticlesController@searchArticle');
        Route::get('/articles/setnext/{id}', 'Admin\ArticlesController@setnext')->name('articles.setnext');
        Route::post('/articles/searchparent', 'Admin\ArticlesController@searchparent');
        Route::get('/articles/setstatus/{id}', 'Admin\ArticlesController@setStatus')->name('articles.setstatus');
        Route::get('/articles/setinteresting/{id}', 'Admin\ArticlesController@setInteresting')->name('articles.setinteresting');
        Route::get('/articles/setpress/{id}', 'Admin\ArticlesController@setPress')->name('articles.setpress');
        Route::post('/articles/sort/{id}', 'Admin\ArticlesController@sort')->name('articles.sort');
        Route::post('/articles/fakeviews/{id}', 'Admin\ArticlesController@fakeViews')->name('articles.fakeviews');
        Route::get('/articles/popup/{id}', 'Admin\ArticlesController@popup')->name('articles.popup');
        Route::resource('/articles', 'Admin\ArticlesController');
    /* END ARTICLES ___________________________________________________________________________________________*/
    /* REPORTS ___________________________________________________________________________________________*/
        Route::get('/reports/search', 'Admin\ReportsController@search')->name('reports.search');
        Route::get('/reports/setstatus/{id}', 'Admin\ReportsController@setStatus')->name('reports.setstatus');
        Route::post('/reports/sort/{id}', 'Admin\ReportsController@sort')->name('reports.sort');
        Route::resource('/reports', 'Admin\ReportsController');
    /* END REPORTS ___________________________________________________________________________________________*/
    /* BRIEFS ___________________________________________________________________________________________*/
        Route::get('/briefs/search', 'Admin\BriefsController@search')->name('briefs.search');
        Route::get('/briefs/setstatus/{id}', 'Admin\BriefsController@setStatus')->name('briefs.setstatus');
        Route::post('/briefs/sort/{id}', 'Admin\BriefsController@sort')->name('briefs.sort');
        Route::resource('/briefs', 'Admin\BriefsController');
    /* END BRIEFS ___________________________________________________________________________________________*/
    /* VIDEOS ___________________________________________________________________________________________*/
        Route::get('/videos/search', 'Admin\VideosController@search')->name('videos.search');
        Route::get('/videos/async', 'Admin\VideosController@async')->name('videos.async');
        Route::resource('/videos', 'Admin\VideosController');
    /* END VIDEOS ___________________________________________________________________________________________*/
    /* SLIDES ___________________________________________________________________________________________*/
        Route::get('/slides/search', 'Admin\SlidesController@search')->name('slides.search');
        Route::get('/slides/async', 'Admin\SlidesController@async')->name('slides.async');
        Route::resource('/slides', 'Admin\SlidesController');
    /* END SLIDES ___________________________________________________________________________________________*/
    /* BANNERS ___________________________________________________________________________________________*/
        // Route::get('/banners/search', 'Admin\BannersController@search')->name('banners.search');
        // Route::get('/banners/async', 'Admin\BannersController@async')->name('banners.async');
        // Route::resource('/banners', 'Admin\BannersController');
    /* END BANNERS ___________________________________________________________________________________________*/
    /* LOCALES ___________________________________________________________________________________________*/
        Route::get('/locale/setstatus/{id}', 'Admin\LocaleController@setStatus');
        Route::post('/locale/sort', 'Admin\LocaleController@sort');
        Route::resource('/locale', 'Admin\LocaleController');
    /* END LOCALES ___________________________________________________________________________________________*/
    /* USERS ___________________________________________________________________________________________*/
        Route::get('/users/delete/{id}', 'Admin\UsersController@destroy')->name('users.delete');
        Route::resource('/users', 'Admin\UsersController');
        Route::get('/mediamanager', 'Admin\MediaController@show')->name('mediamanager.index');
    /* END USERS ___________________________________________________________________________________________*/
    /* GALLERIES ___________________________________________________________________________________________*/
        Route::get('/galleries/getAll', 'Admin\GalleryController@getAllGalleriesInJson');
        Route::get('/galleries/setmonth/{id}', 'Admin\GalleryController@setMonth');
        Route::resource('/galleries', 'Admin\GalleryController');
    /* END GALLERIES ___________________________________________________________________________________________*/
    /* SETTINGS ___________________________________________________________________________________________*/
        Route::get('/settings/{name}', 'Admin\SettingController@settingsfor')->name('settings.for');
        Route::get('/settings', 'Admin\SettingController@index')->name('settings');
        Route::put('/settings/{name}', 'Admin\SettingController@update')->name('settings.update');
    /* END SETTINGS ___________________________________________________________________________________________*/

});

SITE/app/Models/Admin/Gallery.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $fillable = ['name','description','type','params','images'];

    protected $casts = [
        'params' => 'array'
    ];
}

SITE/app/Models/Gallery.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    //
}

SITE/app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Admin\Gallery;
use Illuminate\Http\Request;

use App\Http\Controllers\Admin\GlobalController;

class GalleryController extends GlobalController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $galleries = Gallery::orderBy('created_at', 'DESC')->get();
            return view('admin.pages.gallery.galleries', ['galleries' => $galleries]);
        } catch (\Exception $e) {

        }
    }

    public function getAllGalleriesInJson()
    {
        try {
            $galleries = Gallery::select(['name','id'])->orderBy('created_at', 'DESC')->get();
            return response()->json($galleries);
        } catch (\Exception $e) {

        }
    }

    public function setMonth($id) {
        try {
            $galleryOfTheMonth = Gallery::where('month', 1)->where('id', '!=', $id)->first();
            if ($galleryOfTheMonth) {
                $galleryOfTheMonth->month = false;
                $galleryOfTheMonth->save();
            }
            $gallery = Gallery::find($id);
            $gallery->month = !$gallery->month;
            $gallery->save();
            $notification = [
                'message' => 'Gallery of the month successfully changed',
                'type' => 'success'
            ];
            return redirect()->route('galleries.index')->with('notification', $notification);
        }catch (\Exception $e) {

        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            Gallery::create($request->all());
            return redirect()->route('galleries.index');
        } catch (\Exception $e) {

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Admin\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function show(Gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Admin\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        try {
            return view('admin.pages.gallery.edit', ['gallery' => $gallery]);
        } catch (\Exception $e) {

        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\Admin\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Gallery $gallery)
    {
        try {
            $gallery->update($request->all());
            return redirect()->route('galleries.index');
        } catch (\Exception $e) {

        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Admin\Gallery $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy(Gallery $gallery)
    {
        try {
            $gallery->delete();
            return response()->json(['message' => 'Gallery deleted']);
        } catch (\Exception $e) {
        }
    }
}

SITE/app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Admin\Gallery;
use Illuminate\Http\Request;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Admin\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function show(Gallery $gallery)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Admin\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function edit(Gallery $gallery)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Admin\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Gallery $gallery)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Admin\Gallery  $gallery
     * @return \Illuminate\Http\Response
     */
    public function destroy(Gallery $gallery)
    {
        //
    }
}

SITE/resources/views/admin/pages/gallery/create.blade.php
@extends('admin.layouts.base')
@section('title','::Create Gallery')
@section('js')
    @parent
    <script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
          <h3>New Gallery</h3>
        </div>
        <div class="uk-container uk-container-small">
            <form action="{{route('galleries.store')}}" method="post">
                {{csrf_field()}}
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery name</label>
                        <input type="text" class="uk-input uk-form-large" name="name" value="" placeholder="Gallery name">
                    </div>
                </div>
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery description</label>
                        <textarea name="description" class="uk-textarea uk-form-large" id="" cols="30" rows="5" placeholder="Gallery description"></textarea>
                    </div>
                </div>
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery type</label>
                        <select class="uk-select uk-form-large" name="type">
                            <option value="default">Default</option>
                            <option value="tiles">Tiles</option>
                            <option value="tilesgrid">Tiles grid</option>
                            <option value="carousel">Carousel</option>
                            <option value="compact">Compact</option>
                            <option value="grid">Grid</option>
                            <option value="slider">Slider</option>
                        </select>
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-padding-small">
                        <gallery-images></gallery-images>
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-padding-small">
                        <button class="uk-button uk-button-primary uk-float-right">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

SITE/resources/views/admin/pages/gallery/edit.blade.php
@extends('admin.layouts.base')
@section('title','::Create Gallery')
@section('js')
    @parent
    <script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/tinymce.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('plugins/tinymce/init.js')}}"></script>
@endsection
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
            <h3>Edit Gallery</h3>
        </div>
        <div class="uk-container uk-container-small">
            <form action="{{route('galleries.update',$gallery->id)}}" method="post">
                {{csrf_field()}}
                {{method_field('PUT')}}
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery name</label>
                        <input type="text" class="uk-input uk-form-large" name="name" value="{{$gallery->name}}"
                               placeholder="Gallery name">
                    </div>
                </div>
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery description</label>
                        <textarea name="description" class="uk-textarea uk-form-large" id="" cols="30" rows="5"
                                  placeholder="Gallery description">{{$gallery->description}}</textarea>
                    </div>
                </div>
                <div class="uk-magin">
                    <div class="uk-padding-small">
                        <label class="uk-form-label uk-animation-slide-bottom">Gallery type</label>
                        <select class="uk-select uk-form-large" name="type">
                            <option value="default" @if($gallery->type == 'default') selected @endif>Default</option>
                            <option value="tiles" @if($gallery->type == 'tiles') selected @endif>Tiles</option>
                            <option value="tilesgrid" @if($gallery->type == 'tilesgrid') selected @endif>Tiles grid
                            </option>
                            <option value="carousel" @if($gallery->type == 'carousel') selected @endif>Carousel</option>
                            <option value="compact" @if($gallery->type == 'compact') selected @endif>Compact</option>
                            <option value="grid" @if($gallery->type == 'grid') selected @endif>Grid</option>
                            <option value="slider" @if($gallery->type == 'slider') selected @endif>Slider</option>
                        </select>
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-padding-small">
                        <gallery-images :current="{{json_encode($gallery->images)}}"></gallery-images>
                    </div>
                </div>
                <div class="uk-margin">
                    <div class="uk-padding-small">
                        <button class="uk-button uk-button-primary uk-float-right">Save</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

SITE/resources/views/admin/pages/gallery/galleries.blade.php
@extends('admin.layouts.base')
@section('title','::Galleries')
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
            <a href="{{route('galleries.create')}}" class="uk-icon-button uk-button-secondary uk-float-right"
               uk-icon="icon: plus"></a>
        </div>
        <div class="uk-container uk-container-small">
            <galleries data="{{$galleries}}"></galleries>
        </div>
    </div>
@endsection