SITE/routes/web.php
<?php


use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', 'HomeController@show');
    Route::get('/home', 'HomeController@show')->name('home');
    Route::get('/page/{url}', 'PagesController@show')->name('page');
    Route::get('/reports/{slug}', 'ProductsController@show')->name('reports');

    Route::get('/article/{url}', 'ArticlesController@show')->name('article');
    Route::get('/article/category/{id}', 'ArticlesController@byCategory');



});

Route::get('/home/search', 'HomeController@search')->name('search');
Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');
Route::post('/contactform', 'FormsController@contactForm')->name('contactform');

/* AUTH ROUTES */
Auth::routes();
/* END AUTH ROUTES */

/* ADMIN ROUTES _________________________________________________________________________________________ */
Route::group(['prefix' => 'admin', 'middleware' => ['auth']], function () {
        Route::get('/', 'Admin\HomeController@show');
    /* PAGES ___________________________________________________________________________________________*/
        Route::post('/pages/sort', 'Admin\PagesController@sort');
        Route::resource('/pages', 'Admin\PagesController');
    /* END PAGES ___________________________________________________________________________________________*/
    /* CATEGORIES ___________________________________________________________________________________________*/
        // Route::post('/categories/sort', 'Admin\CategoriesController@sort');
        // Route::resource('/categories', 'Admin\CategoriesController');
    /* END CATEGORIES ___________________________________________________________________________________________*/
    /* ARTICLES ___________________________________________________________________________________________*/
        Route::get('/articles/search', 'Admin\ArticlesController@search')->name('articles.search');
        Route::get('/articles/searcharticle', 'Admin\ArticlesController@searchArticle');
        Route::get('/articles/setnext/{id}', 'Admin\ArticlesController@setnext')->name('articles.setnext');
        Route::post('/articles/searchparent', 'Admin\ArticlesController@searchparent');
        Route::get('/articles/setstatus/{id}', 'Admin\ArticlesController@setStatus')->name('articles.setstatus');
        Route::get('/articles/setinteresting/{id}', 'Admin\ArticlesController@setInteresting')->name('articles.setinteresting');
        Route::get('/articles/setpress/{id}', 'Admin\ArticlesController@setPress')->name('articles.setpress');
        Route::post('/articles/sort/{id}', 'Admin\ArticlesController@sort')->name('articles.sort');
        Route::post('/articles/fakeviews/{id}', 'Admin\ArticlesController@fakeViews')->name('articles.fakeviews');
        Route::get('/articles/popup/{id}', 'Admin\ArticlesController@popup')->name('articles.popup');
        Route::resource('/articles', 'Admin\ArticlesController');
    /* END ARTICLES ___________________________________________________________________________________________*/
    /* REPORTS ___________________________________________________________________________________________*/
        Route::get('/reports/search', 'Admin\ReportsController@search')->name('reports.search');
        Route::get('/reports/setstatus/{id}', 'Admin\ReportsController@setStatus')->name('reports.setstatus');
        Route::post('/reports/sort/{id}', 'Admin\ReportsController@sort')->name('reports.sort');
        Route::resource('/reports', 'Admin\ReportsController');
    /* END REPORTS ___________________________________________________________________________________________*/
    /* BRIEFS ___________________________________________________________________________________________*/
        Route::get('/briefs/search', 'Admin\BriefsController@search')->name('briefs.search');
        Route::get('/briefs/setstatus/{id}', 'Admin\BriefsController@setStatus')->name('briefs.setstatus');
        Route::post('/briefs/sort/{id}', 'Admin\BriefsController@sort')->name('briefs.sort');
        Route::resource('/briefs', 'Admin\BriefsController');
    /* END BRIEFS ___________________________________________________________________________________________*/
    /* VIDEOS ___________________________________________________________________________________________*/
        Route::get('/videos/search', 'Admin\VideosController@search')->name('videos.search');
        Route::get('/videos/async', 'Admin\VideosController@async')->name('videos.async');
        Route::resource('/videos', 'Admin\VideosController');
    /* END VIDEOS ___________________________________________________________________________________________*/
    /* SLIDES ___________________________________________________________________________________________*/
        Route::get('/slides/search', 'Admin\SlidesController@search')->name('slides.search');
        Route::get('/slides/async', 'Admin\SlidesController@async')->name('slides.async');
        Route::resource('/slides', 'Admin\SlidesController');
    /* END SLIDES ___________________________________________________________________________________________*/
    /* BANNERS ___________________________________________________________________________________________*/
        // Route::get('/banners/search', 'Admin\BannersController@search')->name('banners.search');
        // Route::get('/banners/async', 'Admin\BannersController@async')->name('banners.async');
        // Route::resource('/banners', 'Admin\BannersController');
    /* END BANNERS ___________________________________________________________________________________________*/
    /* LOCALES ___________________________________________________________________________________________*/
        Route::get('/locale/setstatus/{id}', 'Admin\LocaleController@setStatus');
        Route::post('/locale/sort', 'Admin\LocaleController@sort');
        Route::resource('/locale', 'Admin\LocaleController');
    /* END LOCALES ___________________________________________________________________________________________*/
    /* USERS ___________________________________________________________________________________________*/
        Route::get('/users/delete/{id}', 'Admin\UsersController@destroy')->name('users.delete');
        Route::resource('/users', 'Admin\UsersController');
        Route::get('/mediamanager', 'Admin\MediaController@show')->name('mediamanager.index');
    /* END USERS ___________________________________________________________________________________________*/
    /* GALLERIES ___________________________________________________________________________________________*/
        Route::get('/galleries/getAll', 'Admin\GalleryController@getAllGalleriesInJson');
        Route::get('/galleries/setmonth/{id}', 'Admin\GalleryController@setMonth');
        Route::resource('/galleries', 'Admin\GalleryController');
    /* END GALLERIES ___________________________________________________________________________________________*/
    /* SETTINGS ___________________________________________________________________________________________*/
        Route::get('/settings/{name}', 'Admin\SettingController@settingsfor')->name('settings.for');
        Route::get('/settings', 'Admin\SettingController@index')->name('settings');
        Route::put('/settings/{name}', 'Admin\SettingController@update')->name('settings.update');
    /* END SETTINGS ___________________________________________________________________________________________*/

});

SITE/app/Models/Admin/Brief.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class Brief extends Model
{
    protected $table = 'briefs';
    protected $fillable = [
        'name',
        'year',
        'status',
        'slug',
        'file',
        'image',
        'params',
        'pos'
    ];

    protected $casts = [
        'name' => 'array',
        'params' => 'array',
    ];
}

SITE/app/Models/Brief.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Brief extends Model
{
    protected $casts = [
        'name' => 'array',
        'params' => 'array',
    ];
}

SITE/app/Http/Controllers/Admin/BriefsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Admin\Brief;
use Illuminate\Support\Facades\DB;
class BriefsController extends GlobalController
{
    private $roles = ['Super','Admin','Moderator'];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $briefs = Brief::orderBy('pos', 'DESC')->paginate(10);
            return view('admin.pages.briefs.briefs', compact('briefs'));
        } catch (\Exception $e) {

        }
    }

    public function search(Request $request)
    {
        try {
            $field = $request->get('searchfield');
            $briefs = Brief::where('name', 'like', '%' . $field . '%')->orderBy('pos', 'DESC')->paginate(10);
            if (empty($field) || count($briefs) == 0) {
                $notification = [
                    'message' => 'Nothing found',
                    'type' => 'danger'
                ];
                return redirect()->route('briefs.index')->with('notification', $notification);
            }
            return view('admin.pages.briefs.briefs', compact('briefs'));
        } catch (\Exception $e) {

        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            $brief = new Brief();
            return view('admin.pages.briefs.create', compact('brief'));
        } catch (\Exception $e) {

        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try {
            $oldPos = DB::table('briefs')->max('pos');
            $inputs = $request->all();
            $inputs['pos'] = $oldPos + 1;
            Brief::create($inputs);
            $notification = [
                'type' => 'success',
                'message' => 'Brief Saved'
            ];
            return redirect()->route('briefs.index')->with('notification', $notification);
        } catch (\Exception $e) {

        }
    }

    public function setStatus($id)
    {
        $this->checkRole($this->roles);
        try {
            $brief = Brief::find($id);
            $brief->status = !$brief->status;
            $brief->save();
            return response()->json(['message' => 'Status updated']);
        } catch (\Exception $e) {
            return response()->json([], 500);
        }
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Brief $brief
     * @return \Illuminate\Http\Response
     */
    public function show(Brief $brief)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brief $brief
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $brief = Brief::find($id);
            return view('admin.pages.briefs.edit', compact('brief'));
        } catch (\Exception $e) {

        }
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Brief $brief
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brief $brief)
    {
        try {
            $inputs = $request->all();
            $brief->update($inputs);
            $notification = [
                'type' => 'success',
                'message' => 'Brief Updated'
            ];
            return redirect()->route('briefs.index')->with('notification', $notification);
        } catch (\Exception $e) {
        }
    }

    public function sort(Request $request, $id)
    {
        $this->checkRole($this->roles);
        try {
            $pos = $request->input('newpos');
            $currentpos = $request->input('pos');
            if ($pos === 1) {
                $oldPos = Brief::where('pos', '<', $currentpos)->max('pos');
            } elseif ($pos === -1) {
                $oldPos = Brief::where('pos', '>', $currentpos)->min('pos');
            }
            if ($oldPos) {
                $oldArticle = Brief::where('pos', $oldPos)->first();
                $prevpos = $oldArticle->pos;
                $oldArticle->update(['pos' => $currentpos]);
                $brief = Brief::find($id);
                $brief->update(['pos' => $prevpos]);
                return response()->json(['message' => 'Sorted'], 200);
            } else {
                return response()->json(['message' => 'Not sorted', 'type' => 'warning'], 200);
            }
        } catch (\Exception $e) {
            return response()->json([], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brief $brief
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brief $brief)
    {
        $this->checkRole($this->roles);
        try {
            $brief->delete();
            return response()->json(['message' => 'Deleted'], 200);
        } catch (\Exception $e) {
            return response()->json([], 500);
        }

    }
}

SITE/resources/views/admin/pages/briefs/_form.blade.php
<div class="uk-margin uk-child-width-1-3" uk-grid>
    <div>
        <div class="uk-form-label uk-animation-slide-bottom">Name</div>
        <localized-input input-name="name" class-name="uk-input uk-form-large" id="translit-it" placeholder="Report name" available-data="{{$brief->name ? json_encode($brief->name) : null}}">
        </localized-input>
    </div>
    <div>
        <div class="uk-form-label uk-animation-slide-bottom">Slug</div>
        <slug inputname="slug" oldval="{{old('url', $brief->slug)}}"></slug>
    </div>
    <div>
        <div class="uk-form-label uk-animation-slide-bottom">Year</div>
        <input type="text" name="year" class="uk-input uk-form-large" value="{{old('url', $brief->year)}}" placeholder="Year">
    </div>
</div>
<div class="uk-margin" uk-grid>
    <div class="uk-width-1-3">
        <file-input inputname="file" file="{{old('file', $brief->file)}}"></file-input>
    </div>
    <div class="uk-width-2-3">
        <imageinput inputname="image" btn="image" img="{{old('image', $brief->image)}}"></imageinput>
    </div>

</div>

SITE/resources/views/admin/pages/briefs/briefs.blade.php
@extends('admin.layouts.base')
@section('title', '::Briefly')
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small uk-margin-bottom">
            <div uk-grid>
                <div class="uk-width-5-6">
                    <form method="GET" action="{{route('briefs.search')}}">
                        <button class="uk-icon-button uk-button-primary" uk-icon="icon: search"></button>
                        <div uk-form-custom>
                            <input class="uk-input uk-form-width-medium uk-border-rounded" name="searchfield"
                                   type="text" placeholder="Search">
                        </div>
                    </form>
                </div>
                <div class="uk-width-1-6">
                    <a href="{{route('briefs.create')}}" class="uk-icon-button uk-button-secondary uk-float-right"
                       uk-icon="icon: plus"></a>
                </div>
            </div>
        </div>
        <div class="uk-container uk-container-small">
            <div class="uk-grid-medium uk-child-width-1-1@s uk-child-width-1-2@m uk-child-width-1-3@l uk-text-center"
                 uk-grid-parallax uk-scrollspy="target: > div; cls:uk-animation-scale-up; delay: 500">
                @foreach($briefs as $brief)
                    <brief item="{{$brief}}" default-locale="{{env('DEFAULTLOCALE')}}"></brief>
                @endforeach
            </div>
            <div class="uk-margin uk-flex uk-padding-small">
                <div class="uk-margin-auto">
                    {{$briefs->links('vendor.pagination.uikit')}}
                </div>
            </div>
        </div>
    </div>
@endsection

SITE/resources/views/admin/pages/briefs/create.blade.php
@extends('admin.layouts.base')
@section('title', '::New report')
@section('js')
    @parent
    <script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
@endsection
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small head-font">
            @include('admin.partials.locale-toggler')
            <form action="{{route('briefs.store')}}" method="post">
                {{ csrf_field() }}
                @include('admin.pages.briefs._form')
                <div class="uk-margin">
                    <button class="uk-button uk-button-secondary uk-float-right">Save</button>
                </div>
            </form>
        </div>
    </div>

@endsection

SITE/resources/views/admin/pages/briefs/edit.blade.php
@extends('admin.layouts.base')
@section('title', '::New Reports')
@section('js')
    @parent
    <script type="text/javascript" src="{{asset('plugins/moxiemanager/js/moxman.loader.min.js')}}"></script>
@endsection
@section('content')
    <div class="uk-section">
        <div class="uk-container uk-container-small head-font">
            @include('admin.partials.locale-toggler')
            <form action="{{route('briefs.update', $report->id)}}" method="POST">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                @include('admin.pages.briefs._form')
                <div class="uk-margin">
                    <a href="{{route('briefs.index')}}" class="uk-button uk-button-danger uk-float-left">Exit without
                        saving</a>
                    <button class="uk-button uk-button-secondary uk-float-right">Save</button>
                </div>
            </form>
        </div>
    </div>
@endsection